---
version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  flog:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
    config:
      file: .reek.yml
  rubocop:
    enabled: true
    channel: rubocop-0-63
    config:
      file: .rubocop.yml

exclude_patterns:
  - "doc/"
  - "docs/"
  - "gemfiles/"
  - "pkg/"
  - "lib/stub_requests/core_ext/"
