require:
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - "Rakefile"
    - "lib/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - ".simplecov"
  Exclude:
    - "lib/stub_requests/core_ext/**/*"
    - "Gemfile.lock"
    - "bin/setup"
    - "gemfiles/**/*"

Layout/IndentArray:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 38

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*.rb'
    - '**/*.rake'

Metrics/PerceivedComplexity:
  Max: 8

Naming/FileName:
  Exclude:
    - '**/Gemfile'

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - ex
    - id

AlignLeftLetBrace:
  Enabled: true

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - given
    - for
    - and

RSpec/EmptyExampleGroup:
  Enabled: false
  CustomIncludeMethods:
    - let!
    - specfify!

RSpec/FilePath:
  Exclude:
    - spec/stub_requests/webmock/builder_spec.rb

RSpec/ImplicitSubject:
  Enabled: false
  EnforcedStyle: single_statement_only

RSpec/MultipleDescribes:
  Exclude:
    - spec/stub_requests/core_ext/object/blank_spec.rb

RSpec/NamedSubject:
  Exclude:
    - spec/stub_requests/core_ext/object/blank_spec.rb

RSpec/NestedGroups:
  Max: 4

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
  AllowSafeAssignment: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
